trigger:
- main
- develop
- feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: '--configuration $(buildConfiguration)'
    publishWebProjects: true
  displayName: 'dotnet publish $(buildConfiguration)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'janc'
    appType: 'webAppLinux'
    appName: 'janc'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'DOTNETCORE|6.0'